### ISSUE TITLE
Duplicate event entries in Gminder

### ISSUE THREAD

**Issue by TekBear** [milowg/GMinder#17] opened 2015-12-02 13:05 UTC
When I start up Gminder everything looks fine, check back 30min later and seeing lost of calendar entries duplicated. I can do clear events menu option followed by refresh events  and restart Gminder and goes back to normal. When I check back 30 min later the problem is back. Here is an example (attached) some duplicates in a public calendar,  some in my personal calendar, some are past events, some are future and not every entry is duplicated. 

Anyone able to reproduce this ?

![gminder 30min dup entries back](https://cloud.githubusercontent.com/assets/5044866/11531426/c4cbfbd4-9937-11e5-8dbb-6d0bdcd278fc.jpg)

win xp SP3 + dot net 4.0.3.x + Gminder 1.4.0.3

**Comment by milowg** [comment] 2015-12-03 14:00
I've been seeing the same thing as of a few days ago. I will take a look when I can.

**Comment by TekBear** [comment] 2015-12-07 19:19
@milowg  Gil are you still seeing the problem?   For the last few hours it seems ok now

**Comment by milowg** [comment] 2015-12-07 19:26
I haven't seen it today and have not had a chance to look through the code and reproduce. It's possible that this was due to a Google glitch.

**Comment by milowg** [comment] 2015-12-17 18:56
Still not seeing the duplicates. @TekBear  are you? If not I will close this and chalk it up to a Google issue

**Comment by milowg** [comment] 2016-01-28 03:47
Reopening issue as I've seen it again. I am working on tracking it down and fixing..

**Comment by milowg** [comment] 2016-02-05 02:10
Fixed in the v1.4.0.4, now available for download.

**Closed by milowg** 2016-02-05 02:10 UTC
