### ISSUE TITLE
Installation issues and questions

### ISSUE THREAD

**Issue by TekBear** [milowg/GMinder#5] opened 2015-04-19 09:26 UTC
Hi Gil,

Great to see this app running again thank you. This is for feedback to help others than may experience installation issues like I did. And a few questions.

Issue 1:
I installed the GMinder-1.4.0.1.zip when I tried to login I got message "about to open browser"  clicked OK and got message "Can't access Google calendar account" and now web page opened in browser. 

Message in "%appdata%\..\Local Settings\Application Data\IsolatedStorage\<blah blah>\Files\ErrorLog.txt" 
"19-04-2015 02:53:45 - Unknown Error: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
                      Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
"

Solution: 
Message indicates missing updates installed "Update 4.0.3 for Microsoft .NET Framework 4 – Runtime Update (KB2600211) " reboot and got to web page.

Issue 2
When I accepted GMinder access it got caught by Firefox + Noscript ABE (application boundaries enforcer) - see http://i.imgur.com/r6Xz1PO.png. 

Solution:
I had to temporarily disable ABE feature, shut GMinder and try again. Once I did that you should see window https://i.imgur.com/m1riYiD.png once you see that click GMinder download button and choose calendars you want to be notified about.

General observations:
%USERPROFILE%\Local Settings\Application Data\ReflectiveCode.com\GMinder.exe_Url_difvun5xsqx4ygp4ofqcte1kh5eigtmo\1.3.1.0\user.config is no longer used and replaced by  %USERPROFILE%\Local Settings\Application Data\ReflectiveCode\GMinder.exe_Url_lz3af1lmprbiz43nwsmkabm0gjqg4u3z\1.4.0.1\user.config (useful if your can't remember your old sound file or color choices)

On first use I got an alert sound for missed past event (I guess) I did not recognize it are you using another sound?

Can you help with these general questions:
On first use I got an alert sound for missed past event (I guess) I did not recognize it are you using another sound?

In previous version, had it working fine until API was deprecated.  I setup app key at https://security.google.com/settings/security/apppasswords?pli=1
and that is still there.  Is that still used or can I delete it?

In "%appdata%\..\Local Settings\Application Data\IsolatedStorage\<blah blah>\Files\Calendars.xml" is no longer updated. Is an XML still created somewhere? Is errolog.txt is the only thing I need to keep in this folder?

Platform: MS .NET Framework v4.0.030319 + win XP
-- Scott

**Comment by TekBear** [comment] 2015-04-19 09:35
Sent donation "...2846" as per details mentioned in issue #2

**Comment by noticz** [comment] 2015-04-22 15:45
I am having a similar problem, this has only happened on one of the workstations out of five. The weird thing is that the computers all have the same exact software and updates on it so I have no idea how to fix it. Let me know your thoughts please!

![2015-04-16_172056](https://cloud.githubusercontent.com/assets/11874318/7278687/468cb72c-e8d4-11e4-9fd8-73fd5691c43e.png)

**Comment by TekBear** [comment] 2015-04-24 21:09
Try switching default web browser before you do login and see if it makes any difference.

Anything in event log?  Can you find the error log on XP path is in "%appdata%\IsolatedStorage\\\<blah blah\>\Files\ErrorLog.txt" and does it have any message at time near your problem?

**Comment by milowg** [comment] 2015-04-28 21:49
@noticz  are you still seeing this issue? Are you logging in when the browser pops up?

I've moved the calendar settings so they don't change every upgrade. They are now located here (you type this into the Run prompt):
%appdata%\GMinder

I've also fixed it so the other settings (like colors) are moved to the new folder when you upgrade. LMK if that is not working for you.

**Comment by TekBear** [comment] 2015-07-13 18:31
Login button has stopped working: I press it web page opens and I press accept button and get "Can't access Google account" pop up message is there a way to manually add  details to setting file?

Errorlog.txt has message:
> 14-07-2015 02:26:23 - Unknown Error: One or more errors occurred.
>                      One or more errors occurred.
> An error occurred while sending the request.

**Comment by milowg** [comment] 2015-07-14 16:41
I can't reproduce this on Windows 7. Do you have Windows 7 running somewhere so you can verify?

**Comment by TekBear** [comment] 2015-07-19 23:30
I don't have Win 7 but I tested on XP SP3 + Chrome browser and there was no problem as described, so it looks like any thing prior to that has an issue. I am just mentioning the issue to see if anyone else can confirm same result (with XP SP2). The is no expectation that this is fixable in that configuration.

**Comment by milowg** [comment] 2017-02-14 03:37
I'm closing this as Chrome doesn't even support Windows XP any longer.

**Closed by milowg** 2017-02-14 03:37 UTC

**Comment by TekBear** [comment] 2017-02-14 08:02
Yes you are correct there is no official Chrome support although sign-in/auth does still work with Chrome+XP SP3 last time a checked,
